title: noumeno.us
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.875
  brandStrength: 0.625
  lightness: 0.5625
  brandColors:
    - '#FFFFFF'
    - '#4371BC'
    - '#273039'
    - '#BABFC2'
    - '#6C6762'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Noumenon Designs
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1558974420186132
layout_spectrum: 0.49792
