layout_spectrum: 0.707374898949638
typography_spectrum: 0.20165427681058645
color:
  saturation: 0.03793178522028029
  brandStrength: 0.8303918198216707
  lightness: 0.8663830740842968
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  rhythmicContrast: 0.9015496228821576
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/51862701-3e8c-4ad5-a2e8-3b4357bde966.jpg
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Martin Nibali
  email: martin@noumeno.us
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/68a3ddf4-b50f-4559-aff2-b6115bfa17fe.png
name: Noumenon Designs
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: contact
    id: 89298d88-e1de-4910-9430-dea4a382ab83
    type: content
  - name: portfolio
    id: 3d1696dc-56eb-4fa5-ba43-b5d80d91b062
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/385b66cd-fb78-4d9f-9092-b3efb4757d82.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Noumenon Designs
description: fundamental. phenomenal.
purpose: []
