analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.49792
title: noumeno.us
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.875
  brandStrength: 0.625
  rhythmicContrast: 0.75
  brandColors:
    - '#415755'
    - '#869092'
    - '#feffff'
    - '#182221'
    - '#c1c3c2'
  lightness: 0.5625
purpose: []
favicon: null
name: Noumenon Designs
typography_spectrum: 0.1558974420186132
