name: Noumenon Designs
favicon: null
layout_spectrum: 0.19396256771869957
typography_spectrum: 0.15589744201861322
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6380872612353414
  lightness: 0.5672615237999707
  saturation: 0.8867199462838471
  rhythmicContrast: 0.6951200235635042
purpose: []
